apiVersion: v1
kind: ConfigMap
metadata:
  name: altermanger-config
  labels:
    name: altermanger-config
  namespace: kube-system
data:
  altermanger-config.yml: |-
    global:
      resolve_timeout: 5m
    route:
      receiver: webhook
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 1h
      group_by: [citest]
      routes:
      - receiver: webhook
        group_wait: 10s
        match:
          team: container
    receivers:
    - name: webhook
      webhook_configs:
      - url: http://prometheus-webhook-dingtalk:39093/dingtalk/node/send
        send_resolved: true
