kind: Deployment
apiVersion: apps/v1
metadata:
  name: kube-state-metrics
  namespace: kube-system
  selfLink: /apis/apps/v1/namespaces/kube-system/deployments/kube-state-metrics
  uid: dc0e1a14-17a9-11e9-bbbc-fa163eb8f89d
  resourceVersion: '10913395'
  generation: 1
  creationTimestamp: '2019-01-14T03:09:52Z'
  labels:
    grafanak8sapp: 'true'
    k8s-app: kube-state-metrics
  annotations:
    deployment.kubernetes.io/revision: '1'
spec:
  replicas: 1
  selector:
    matchLabels:
      grafanak8sapp: 'true'
      k8s-app: kube-state-metrics
  template:
    metadata:
      creationTimestamp: null
      labels:
        grafanak8sapp: 'true'
        k8s-app: kube-state-metrics
 
    spec:
      serviceAccountName: prometheus
      containers:
        - name: kube-state-metrics
          image: 'quay.io/coreos/kube-state-metrics:v1.1.0'
          ports:
            - name: http-metrics
              containerPort: 8080
              protocol: TCP
          resources: {}
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 2
  progressDeadlineSeconds: 600

